// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Sergio Martins

import { VerticalBox, Button , LineEdit} from "std-widgets.slint";
export component LoginWindow inherits Rectangle {
    width: 800px;
    height: 800px;
    callback request-login(string, string);

    background: #2f343d;

    Image {
        source: @image-url("assets/icon.png");
        width: 200px;
        height: 200px;
        y: 50px;
        horizontal-alignment: ImageHorizontalAlignment.center;
    }

    Rectangle {
        border-radius: 5px;
        width: 300px;
        height: 300px;
        background: #ffffff;

        VerticalBox {
            width: 100%;
            height: 100%;

            VerticalBox {

                Text {
                    color: #000000;
                    text: "Username";
                }

                username := LineEdit { }
            }

            VerticalBox {
                Text {
                    color: #000000;
                    text: "Password";
                }

                pwd := LineEdit {
                    input-type: password;
                }
            }

            Button {
                text: "Login";
                enabled: username.text != "" && pwd.text != "";
                clicked => {
                    request-login(username.text, pwd.text);
                }
            }
        }
    }
}
