# SPDX-License-Identifier: MIT

name: Sanitizers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sanitizer: ["address", "leak", "memory", "thread"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set rust nightly
        run: |
          rustup default nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Run tests
        run: |
          cargo test -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=${{ matrix.sanitizer }}"
          RC_SLINT_USER: ${{ secrets.RC_SLINT_TEST_USER }}
          RC_SLINT_TEST_USER: ${{ secrets.RC_SLINT_TEST_USER }}
          RC_SLINT_TEST_PWD: ${{ secrets.RC_SLINT_TEST_PWD }}
          RC_SLINT_TEST_URL: ${{ secrets.RC_SLINT_TEST_URL }}
          RC_SLINT_URL: ${{ secrets.RC_SLINT_TEST_URL }}
