# SPDX-License-Identifier: MIT

name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          cargo test
        env:
          RC_SLINT_TEST_USER: ${{ secrets.RC_SLINT_TEST_USER }}
          RC_SLINT_TEST_PWD: ${{ secrets.RC_SLINT_TEST_PWD }}
          RC_SLINT_TEST_URL: ${{ secrets.RC_SLINT_TEST_URL }}
